services:
  - type: web
    name: school-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /

databases:
  - name: school-db
    plan: free
    databaseName: school_system
    user: school_user